# -*- coding: utf-8 -*-
"""BERT_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b47hvX2DNJN_Nc34rlZjSSsVL_UtjGAf
"""

from google.colab import files
uploaded = files.upload()

!pip install transformers datasets scikit-learn -q

import pandas as pd
import numpy as np
from datasets import Dataset, DatasetDict
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import classification_report, accuracy_score, f1_score

train_df = pd.read_csv("psydefconv_train.csv")
test_df = pd.read_csv("psydefconv_test.csv")

train_df = train_df.rename(columns={"current_text": "text"})
test_df = test_df.rename(columns={"current_text": "text"})

train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

dataset = DatasetDict({
    "train": train_dataset,
    "test": test_dataset
})

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, padding="max_length", max_length=128)

dataset = dataset.map(tokenize, batched=True)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=9
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro"),
        "weighted_f1": f1_score(labels, preds, average="weighted")
    }

training_args = TrainingArguments(
    output_dir="./psydef_bert_results",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=4,
    logging_steps=25,
    learning_rate=2e-5
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    compute_metrics=compute_metrics
)

trainer.train()

results = trainer.evaluate()
print("BERT RESULTS:")
print(results)

pred_output = trainer.predict(dataset["test"])
y_pred = np.argmax(pred_output.predictions, axis=1)
y_true = pred_output.label_ids

print("\nClassification Report:")
print(classification_report(y_true, y_pred, digits=3))

import matplotlib.pyplot as plt

models = ["SVM", "BERT"]
accuracy = [0.597, 0.621]

plt.figure()
plt.bar(models, accuracy)
plt.title("Model Accuracy Comparison")
plt.xlabel("Model")
plt.ylabel("Accuracy")

plt.show()

import matplotlib.pyplot as plt

labels = ["0","1","2","3","4","5","6","7","8"]
f1_scores = [0.787,0,0,0,0,0,0.188,0.735,0]

plt.figure()
plt.bar(labels, f1_scores)

plt.title("BERT F1 Score by Defense Level")
plt.xlabel("Defense Level")
plt.ylabel("F1 Score")

plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d')

plt.title("Confusion Matrix (BERT)")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()